### PR TITLE
Run reconcilation periodically

### PR DESCRIPTION
**Pull request by barchw**
**Description**

Changes proposed in this pull request:

- Run reconcilation periodically (set to 30 minutes)
- If reconcilation reports conflict run the reconcilation faster
- Don't re-reconcile ConfigMap

**Related issue(s)**

- https://github.com/kyma-project/kyma/issues/10146

### CODE REVIEW

**Comment by barchw** [comment]
Fixes https://github.com/kyma-project/kyma/issues/10146

**Review by werdes72 — APPROVED** [review]

**Pull request merged**
