### PR TITLE
Provide make target to generate CRD with patches

### PR DESCRIPTION
**Pull request by cnvergence**
Make it easier to maintain crds in different projects
- https://github.com/kyma-project/kyma/blob/main/installation/resources/crds/api-gateway/apirules.gateway.crd.yaml

### CODE REVIEW

**Comment by barchw** [comment]
I would say this is unnecessary, as the conversion is applied as kustomization patch in https://github.com/kyma-project/api-gateway/blob/main/config/crd/patches/webhook_in_apirules.yaml

**Comment by cnvergence** [comment]
> I would say this is unnecessary, as the conversion is applied as kustomization patch in https://github.com/kyma-project/api-gateway/blob/main/config/crd/patches/webhook_in_apirules.yaml

Alright, shall we then generate and keep the outcome CRD here?

**Review by barchw — APPROVED** [review]

**Pull request merged**
